/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: dangling_library_doc_comments, constant_identifier_names

import 'package:flutter/material.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData location =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_outline =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData college =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commerical_building =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask =
      IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_arrow =
      IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open =
      IconData(0xf518, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions =
      IconData(0xf5eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_location =
      IconData(0xf689, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class CategoryIcon {
  static final icons = {
    'building': const Icon(
      CustomIcons.commerical_building,
      size: 18 * 0.8,
      color: Color(0xFFF93939),
    ),
    'clinic': const Icon(
      Icons.health_and_safety_outlined,
      color: Color(0xFFFF1F1F),
      size: 18 * 1.1,
    ),
    'college': const Icon(
      Icons.school,
      size: 18,
      color: Colors.blueAccent,
    ),
    'food': const Icon(
      Icons.restaurant,
      size: 18 * 0.9,
      color: Color(0xFFF48C15),
    ),
    'hall': const Icon(
      CustomIcons.commerical_building,
      size: 18 * 0.8,
      color: Color(0xFFF93939),
    ),
    'hostel': const Icon(
      Icons.local_hotel_rounded,
      size: 18,
      color: Colors.yellow,
    ),
    'laboratory': const Icon(
      CustomIcons.flask,
      size: 18 * 0.8,
      color: Colors.purpleAccent,
    ),
    'library': const Icon(
      CustomIcons.book_open,
      size: 18 * 0.8,
      color: Colors.deepOrange,
    ),
    'office': const Icon(
      Icons.cases_rounded,
      size: 18 * 0.9,
      color: Colors.brown,
    ),
    'park': const Icon(
      Icons.park,
      size: 18,
      color: Colors.green,
    ),
    'school': const Icon(
      Icons.school,
      size: 18,
      color: Colors.deepOrangeAccent,
    ),
    'security': const Icon(
      Icons.security_outlined,
      size: 18,
      color: Colors.deepPurple,
    ),
    'sports': const Icon(
      Icons.sports_volleyball_outlined,
      size: 18,
      color: Colors.blue,
    ),
    'under construction': const Icon(
      Icons.construction,
      color: Color(0xFFA8A31F),
      size: 18,
    ),
  };
}
